### PR TITLE
fix(gateway): question marks in url.Path when redirecting

### LINKED ISSUE #1201: IPFS Companion cannot handle a ? in the title of a document.
**Describe the bug**
* Files such as e.g. https://mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf result in [the following erroneous HTTP session](https://github.com/ipfs/ipfs-companion/files/11497121/mindwar.net.ipns.localhost.har.zip):

```yaml
301 GET https://mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf
    Request headers
    Response headers (status = 301)
        Accept-Ranges: bytes
        Access-Control-Allow-Headers: Content-Type
        Access-Control-Allow-Headers: Range
        Access-Control-Allow-Headers: User-Agent
        Access-Control-Allow-Headers: X-Requested-With
        Access-Control-Allow-Methods: GET
        Access-Control-Allow-Origin: *
        Access-Control-Expose-Headers: Content-Length
        Access-Control-Expose-Headers: Content-Range
        Access-Control-Expose-Headers: X-Chunked-Output
        Access-Control-Expose-Headers: X-Ipfs-Path
        Access-Control-Expose-Headers: X-Ipfs-Roots
        Access-Control-Expose-Headers: X-Stream-Output
        Content-Length: 180941
        Content-Type: application/pdf
        Date: Wed, 17 May 2023 10:18:16 GMT
        Etag: "QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3"
        Last-Modified: Wed, 17 May 2023 10:18:16 GMT
        Location: http://mindwar.net.ipns.localhost:8080/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference?.pdf
        X-DNS-Prefetch-Control: off
        X-Ipfs-Path: /ipns/mindwar.net/Jim Stewartson v. QAnon â Can you spot the difference?.pdf
        X-Ipfs-Roots: QmV7UhgGn2qULg9Wwz76if557XrwDbrSkxQGmhtya77a7R,QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3

404 GET http://localhost:8080/ipns/mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf
    Request headers
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q
                =0.7
        Accept-Encoding: gzip, deflate, br
        Accept-Language: en-US,en;q=0.9,es-419;q=0.8,es;q=0.7
        Connection: keep-alive
        DNT: 1
        Host: mindwar.net.ipns.localhost:8080
        Sec-Fetch-Dest: document
        Sec-Fetch-Mode: navigate
        Sec-Fetch-Site: none
        Sec-Fetch-User: ?1
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
        sec-ch-ua: "Not:A-Brand";v="99", "Chromium";v="112"
        sec-ch-ua-mobile: ?0
        sec-ch-ua-platform: "Linux"
    Response headers (status = 404)
        Access-Control-Allow-Headers: Content-Type
        Access-Control-Allow-Headers: Range
        Access-Control-Allow-Headers: User-Agent
        Access-Control-Allow-Headers: X-Requested-With
        Access-Control-Allow-Methods: GET
        Access-Control-Allow-Origin: *
        Access-Control-Expose-Headers: Content-Length
        Access-Control-Expose-Headers: Content-Range
        Access-Control-Expose-Headers: X-Chunked-Output
        Access-Control-Expose-Headers: X-Ipfs-Path
        Access-Control-Expose-Headers: X-Ipfs-Roots
        Access-Control-Expose-Headers: X-Stream-Output
        Content-Length: 221
        Content-Type: text/plain; charset=utf-8
        Date: Wed, 17 May 2023 10:38:01 GMT
        X-Content-Type-Options: nosniff
        X-Ipfs-Path: /ipns/mindwar.net/Jim Stewartson v. QAnon â Can you spot the difference

404 GET http://mindwar.net.ipns.localhost:8080/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference?.pdf
    Request headers
        DNT: 1
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
        sec-ch-ua: "Not:A-Brand";v="99", "Chromium";v="112"
        sec-ch-ua-mobile: ?0
        sec-ch-ua-platform: "Linux"
    Response headers (status = 404)
        Access-Control-Allow-Headers: Content-Type
        Access-Control-Allow-Headers: Range
        Access-Control-Allow-Headers: User-Agent
        Access-Control-Allow-Headers: X-Requested-With
        Access-Control-Allow-Methods: GET
        Access-Control-Allow-Origin: *
        Access-Control-Expose-Headers: Content-Length
        Access-Control-Expose-Headers: Content-Range
        Access-Control-Expose-Headers: X-Chunked-Output
        Access-Control-Expose-Headers: X-Ipfs-Path
        Access-Control-Expose-Headers: X-Ipfs-Roots
        Access-Control-Expose-Headers: X-Stream-Output
        Content-Length: 221
        Content-Type: text/plain; charset=utf-8
        Date: Wed, 17 May 2023 10:38:01 GMT
        X-Content-Type-Options: nosniff
        X-DNS-Prefetch-Control: off
        X-Ipfs-Path: /ipns/mindwar.net/Jim Stewartson v. QAnon — Can you spot the difference
```

IPFS Companion incorrectly converts `%3F` to `?`.

**To Reproduce**
1. Self evident.

**Expected behavior**
Self-evident.

kubo itself is fully capable of resolving `/ipns/mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf` to QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3.

```
$ ipfs get --progress=0 "$(ipfs resolve /ipns/mindwar.net/'Jim Stewartson v. QAnon — Can you spot the difference?.pdf')"
Saving file(s) to QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3
```

But perhaps is the cause of the bug because note its Location return here:

```bash
$ curl --head 'localhost:8080/ipns/mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf'
```
```http
HTTP/1.1 301 Moved Permanently
Accept-Ranges: bytes
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Headers: Range
Access-Control-Allow-Headers: User-Agent
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length
Access-Control-Expose-Headers: Content-Range
Access-Control-Expose-Headers: X-Chunked-Output
Access-Control-Expose-Headers: X-Ipfs-Path
Access-Control-Expose-Headers: X-Ipfs-Roots
Access-Control-Expose-Headers: X-Stream-Output
Content-Length: 180941
Content-Type: application/pdf
Etag: "QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3"
Last-Modified: Wed, 17 May 2023 11:00:40 GMT
Location: http://mindwar.net.ipns.localhost:8080/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference?.pdf
X-Ipfs-Path: /ipns/mindwar.net/Jim Stewartson v. QAnon — Can you spot the difference?.pdf
X-Ipfs-Roots: QmV7UhgGn2qULg9Wwz76if557XrwDbrSkxQGmhtya77a7R,QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3
Date: Wed, 17 May 2023 11:00:40 GMT
```

I'll report up there too.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Linux debutanuki 6.3.2-zen1-1-zen #​1 ZEN SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:19 +0000 x86_64 GNU/Linux
 - Browser: ungoogled-chromium-bin 112.0.5615.165-1
 - Version: 2.22.1

**Smartphone (please complete the following information):**
N/A.

### LINKED ISSUE #9882: Kubo mishandles `?` in path names in IPNS context, confusing standards-conformant browsers
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text
Kubo version: 0.20.0-b8c472500
Repo version: 13
System version: amd64/linux
Golang version: go1.20.4
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip4/0.0.0.0/udp/4001/quic-v1",
      "/ip4/0.0.0.0/udp/4001/quic-v1/webtransport",
      "/ip6/::/udp/4001/quic",
      "/ip6/::/udp/4001/quic-v1",
      "/ip6/::/udp/4001/quic-v1/webtransport"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": false
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "OptimisticProvide": false,
    "OptimisticProvideJobsPoolSize": 0,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": ""
  },
  "Identity": {
    "PeerID": "12D3KooWAPaUCbcb5Q7GGgVnKpTwppgiXKFu47aEvwB3zaokGjcS"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {},
  "Routing": {
    "Methods": null,
    "Routers": null
  },
  "Swarm": {
    "AddrFilters": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "ConnMgr": {},
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": true,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {
      "Limits": {}
    },
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

I thought this was a bug in Chrome extension IPFS Companion but Kubo itself is giving invalid `Location` header. Observe:

```bash
$ curl --head 'localhost:8080/ipns/mindwar.net/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf'
```
```http
HTTP/1.1 301 Moved Permanently
Accept-Ranges: bytes
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Headers: Range
Access-Control-Allow-Headers: User-Agent
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length
Access-Control-Expose-Headers: Content-Range
Access-Control-Expose-Headers: X-Chunked-Output
Access-Control-Expose-Headers: X-Ipfs-Path
Access-Control-Expose-Headers: X-Ipfs-Roots
Access-Control-Expose-Headers: X-Stream-Output
Content-Length: 180941
Content-Type: application/pdf
Etag: "QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3"
Last-Modified: Wed, 17 May 2023 11:00:40 GMT
Location: http://mindwar.net.ipns.localhost:8080/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference?.pdf
X-Ipfs-Path: /ipns/mindwar.net/Jim Stewartson v. QAnon — Can you spot the difference?.pdf
X-Ipfs-Roots: QmV7UhgGn2qULg9Wwz76if557XrwDbrSkxQGmhtya77a7R,QmXZdegY4BBHdjMeCadhCbciziQTFynkApbgtDGbodhsz3
Date: Wed, 17 May 2023 11:00:40 GMT
```

It ought to be returning instead:

```http
Location: http://mindwar.net.ipns.localhost:8080/Jim%20Stewartson%20v.%20QAnon%20%E2%80%94%20Can%20you%20spot%20the%20difference%3F.pdf
```

IPNS redirection breaks on files containing ASCII question mark (`?`), which is totally valid to have in a filename.

_Cf._ ipfs/ipfs-companion#1201

### PR DESCRIPTION
**Pull request by hacdias**
Fixes https://github.com/ipfs/kubo/issues/9882, fixes https://github.com/ipfs/ipfs-companion/issues/1201. I updated `toSubdomainURL` to use the `url.URL` struct from Go to build the final URL.  The problem was that `rest` was the original, decoded, `r.URL.Path` and it contains a `?`. When Go parses it, it'd consider it as a query element, rightly so.

Kubo PR: https://github.com/ipfs/kubo/pull/9894

### CODE REVIEW

File: gateway/hostname.go [hunk 1]
```diff
@@ -471,15 +452,23 @@ func toSubdomainURL(hostname, path string, r *http.Request, inlineDNSLink bool,
...
+	if rest == "" {
+		u.Path = "/"
+	} else {
+		u.Path = rest
+	}
+	if isHTTPS {
+		u.Scheme = "https"
+	} else {
+		u.Scheme = "http"
+	}
```
Comment (whizzzkid) [inline gateway/hostname.go]: you can maybe set defaults and then just change the values if defaults are not true, no `else` needed.

**Review by lidel — APPROVED** [review]
I've tested this in Kubo (https://github.com/ipfs/kubo/pull/9894) and works as expected.
I've resolved conflicts in https://github.com/ipfs/boxo/pull/313/commits/77afd71ae5c877d0adc420cd54e522a4f76b83ba  and tested again locally, still good.

Merging, to bubble up to https://github.com/ipfs/kubo/pull/9894. 
@hacdias please see my comment there for next steps :pray:
